### ISSUE TITLE
Update to 1.14

### ISSUE THREAD

**Issue by IgazHarcos** [RenCloud/scs-sdk-plugin#116]
Hi!

Just asking, if there wil lbe any update for this?

as I can see, the latest version is 1.12 on the release page, but there is an 1.14 version, if I am correect.

I want to use, for example cargo damage on a dashboard, but it is not presented in 1.12.

Are you plannig any update?

Thanks for your answer!

**Comment by RenCloud** [comment]
Hi, SDK Version 1.14 is supported and the version that is used in that release. The only thing missing from that release and the current master branch is a race condition fix. That is currently only part of the dev branch, because I forgot to merge it into the master branch. 

However, there is currently no support for the input devices that were added in that release.

1.12 is the version of the release of this repository.

**Comment by IgazHarcos** [comment]
Hi!

Now I see in the Demo the value I looked for. It's really nice! 

Did you know, if anybody made something like Finbit's telemtry server with client with your version? Sadly that is not maintained for years and PauloTNCunha is not maintained too.

**Comment by RenCloud** [comment]
At the moment, I think not.

**Comment by IgazHarcos** [comment]
Thank you for your answers!
