### ISSUE TITLE
Job didn't finish if you turn off the game

### ISSUE THREAD

**Issue by domcekplayer** [RenCloud/scs-sdk-plugin#24]
When you finish job in game and turn game off, jobfinished event is not fired. Maybe its same bug like with new route. 
Big thanks for this updated plugin!

**Comment by domcekplayer** [comment]
OK, big thanks! Is there any way to discuss with you? Like discord, skype, etc.

**Comment by RenCloud** [comment]
I create a Discord Server for this project to discuss etc. [Discord](https://discord.gg/JDqkZZd)

The way seems to work. I didn't have the time at the moment to test every case, but for job canceling and deliver the cargo, it works great and for the other cases it should work also.

It now work with the config event [source](https://github.com/RenCloud/scs-sdk-plugin/blob/7b19de1b75d28f8c5a61b5d7d0a70caa01d512cb/scs-telemetry/src/scs_telemetry.cpp#L310).
Every time the event has the id `job` and contain values we are on a job.
If it later comes again, but now it doesn't contain values we are not on a job anymore. 

This should also work for your type of 'bug', because it fires the event at the moment you close the screen where you became the money and experience for the delivery.
