### ISSUE TITLE
Demo Client Error

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [RenCloud/scs-sdk-plugin#26]
Hey, 

First thank you for sdk1.9 and can you help me with this error please. I run debug mode and VS show me this error, but when run DemoClient.exe.. just close after few seconds when I click on my profile, before I click on my profile everything show on about tab.

System.ArgumentException: 'Requested value 'arcade ���������' was not found.'

![value_arcade_error](https://user-images.githubusercontent.com/13278733/50741116-0df1f380-11f9-11e9-9510-c306049996a3.png)

Thank you.

**Comment by RenCloud** [comment]
Hey, 

first thanks for the report ... sadly the next person that have that bug. At my side this problem doesn't show up, so i need to test a few things when i got some time. 

Because of something, that i don't know at the moment, the strings seems to be incorrect in the git version... but not by my local version. Like in the Exception, the strings are created with '���������' in the end and i don't know why that's happen. And because i don't handle a wrong string correctly when converting from string to enum it crash at this point through that bug.

May you could help me to find the problem. I don't know how good your knowledge in c# and c++ is. 
So as a simple start it would be helpful when you could tell me the int(or hex) value of `�`. So i know a bit more what that symbol is. With debug mode it should not be that difficult to get that. 

Or you need a working version you could try to use some previous commits. That bug seems to be created in one of the last commits. But than some features are missing and the object was a bit changed.

**Comment by 15w34r0n3D4y** [comment]
public static T ToEnum<T>(this string enumString) => (T) Enum.Parse(typeof(T), enumString, true);

in extension.cs

**Comment by RenCloud** [comment]
Thanks for that. I will try to create a hotfix in the next days. And because i won't be happy with that, i will add Lines for logging purpose. So that, when something like that happen, you can simple change a variable and a log file will be generated that will help me to fix that bug.

**Comment by RenCloud** [comment]
In a test with another user with the same problems it helped to get a working compiled .dll. 
So it seems that there is may something missing or a header is wrong on the cpp site. 

I will upload a working project with dll the next days. Later i will try to find the header file in cpp that cause that problem.
