### ISSUE TITLE
Is kniffen/TruckSim-Telemetry supported?

### ISSUE THREAD

**Issue by YeapGuy** [RenCloud/scs-sdk-plugin#40]
Hey,
First of all, I don't have any C or C# knowledge whatsoever. Please don't hate me for my dumb question.
Secondly, will this plugin work with https://github.com/kniffen/TruckSim-Telemetry ? There is an open issue on the repo asking for support of your project. It was opened 3 months ago and still not closed. I'm wondering if this plugin works with TruckSim-Telemetry the same way nlhans' plugin did.
Sorry for the badly formulated issue, I can't really express my thoughts in English well 😌. Have a great day.

**Comment by RenCloud** [comment]
Hey, 

Without changes not. The shared memory structure has changed a lot. And with using sdk 1.10 there are a lot more values.

But it should not be that hard to implement the changes. When you understand `index. Js` and ` raw‐data‐from-buffer. Js` you could try to implement the update yourself. If you have questions how to do it i will try to help you. 


However it seems that the project of kniffen did not refresh the data by itself (only when you call a
Method) and because of that it's represent event values plain as boolean values. When you are interested in the events(job finished, toll, fine, etc. ) then a bit more work is needed. But here i can't help you, because i don't know how and if events in javascript works.

**Comment by kniffen** [comment]
@YeapGuy [TruckSim-Telemetry](https://github.com/kniffen/TruckSim-Telemetry) now supports rev.9 of the plugin, will work on rev.10 support next.

**Comment by RenCloud** [comment]
That's nice. I like your Demo Application @kniffen. That remembers me to update my demo application 😄 . 

I will add a link to your project.
