### ISSUE TITLE
RegPlateCountryId

### ISSUE THREAD

**Issue by N95JPL** [RenCloud/scs-sdk-plugin#64]
Hello,
I have noticed some inconsistencies using the
RegPlateCountry & RegPlateCountryId

For the UK it shows
United Kingdom & UK

For France it shows
France & france instead of FR
Using 10.5.1 (SDK 1_11) 
Game Version: ETS2 1.37 Beta

Thanks
Joshua

**Comment by RenCloud** [comment]
Hey,
thanks for the information, but i can't directly do something against that. The values of this fields are from the game. I didn't change them. 

So the inconsistency is coming from SCS. But i'm not sure if this is not intentionally, because the id if more fore code handling and not directly a short form of the country. But that's only a guess. 

Did you now how other countries are displayed? e.g. Germany, Poland, Italy or other long names like Czech Republik.

Also did this already happen before 1.37 beta?
