### ISSUE TITLE
Estimated Arrival Time

### ISSUE THREAD

**Issue by joschiservice** [RenCloud/scs-sdk-plugin#70]
Hello,
Is there a possibility to get the estimated arrival time?

**Comment by joschiservice** [comment]
Nevermind Sorry. I can add the remaining delivery time to the game time

**Comment by N95JPL** [comment]
Couldn't you do this by doing...
`DateTime ArrivalTime = data.CommonValues.GameTime.Date + data.NavigationValues.NavigationTime` this should give you the ETA

**Comment by RenCloud** [comment]
Thanks for the help N95JPL. I'm not quite sure why i didn't added it as a Time/Frequency (datetime) object, but i guess it's because it's a float and in seconds.

Timezones... sadly the SDK doesn't provide information about them. Most features in game came later or until now never to the SDK, 
For the `GameTime` the documentation says `Absolute in-game time.` So it doesn't matter where you are in-game and what settings in-game you have. I guess it was UTC or CET, but i'm not sure i have to check that.

**Comment by N95JPL** [comment]
No problem, glad to assist. The float does make sense once you realise its in Seconds, maybe that needs to be documented somewhere?
and ahh right okay - I assumed, because SCS uses CET on there posts alot that it will be that. Something to bare in mind when showing time. If you have Timezones turned on, you'll need to figure that out in your program!

**Comment by joschiservice** [comment]
Thanks @N95JPL . Thought NavigationTime is the time shown in the route advisor. Well I should have tried this before asking. My bad, but thanks for your help!
