### ISSUE TITLE
Data collect timestamp

### ISSUE THREAD

**Issue by Cheltone** [RenCloud/scs-sdk-plugin#74]
Hello and great work with the SDK! Could you explain how I can extract a timestamp for each point in the exported CSV? Thanks!

**Comment by RenCloud** [comment]
Hi and thanks.

The project didn't create a csv. It creates a shared memory map. The client then read the shared memory and creates a c# object from it. From that you could create a csv. 

What exactly did you expect to have as result?

As timestamp there exist different kind of values
- Telemetry Timestamp (stops when the physic engine is not running/the game is stopped/menu is open/etc)
- Simulation Timestamp 
- Render Timestamp
- In Game time (the current in game time of the selected profile. It is game timezone independent.)

**Comment by Cheltone** [comment]
Thanks for getting back to me! Overall, I am hoping to record vehicle velocity or speed in m/s, acceleration, steering wheel angle, RPM, and breaking. I hope to have each correlated with either the Simulation timestamp or Telemetry and export a CSV for the sim. Is this possible?

Does the Sim timestamp record while the mission is ongoing? If so that might be best.

**Comment by Cheltone** [comment]
Does that all make sense?

**Comment by RenCloud** [comment]
Sorry for the delay. As far as i understand you this should be possible. 


With mission you mean a job? Than yes. All 3 timestamps are changing when the simulation is running (truck drives). Only the telemetry timestamp will stop if stop the simulation. Also all 3 timestamps coming from the sdk.

When you take a look at the demo application you see that it displays the data every 100ms. Instead of rendering the values you would write the needed datafields to a file. If 100ms to slow you could reduce the refresh rate, but that can lead to errors when its to low. Which could be fixed when you only need these few data fields. 


To be more correct when using the `update` flag the data will only be refreshed when the simulation is running. That should be the case for the demo application, but you could change [this line](https://github.com/RenCloud/scs-sdk-plugin/blob/53b9b8a36548efdace16b032a93ce91b31ff2285/scs-client/C%23/SCSSdkClient.Demo/SCSSdkClient.Demo/SCSSdkClientDemo.cs#L77) to see the behavior if you ignore it.
When you ignore that flag the data will be still be updated, but no value will change. Beside one or two.
